"""
Compare features generated by predict() vs predict_batch() to find discrepancies.
"""
from bbl_pipeline.inference.predictor import Predictor
from bbl_pipeline.inference.schema import MatchState as InferenceState
from bbl_pipeline.simulation.state import MatchState as SimState
import pandas as pd

print('=== Feature Comparison: predict() vs predict_batch() ===')
print()

predictor = Predictor.load(
    model_dir='models/t20_female_v3',
    feature_store_dir='data/t20_female_feature_store_v3',
    league='wpl'
)

# Test state: 0/0, start of match
inference_state = InferenceState(
    match_id='test',
    innings=1,
    over=0,
    ball=0,
    current_score=0,
    wickets_lost=0,
    target_runs=None,
    batting_team='GGW',
    bowling_team='UPW',
    batsman_1='Unknown',
    batsman_2='Unknown',
    bowler='Unknown',
    venue='Unknown'
)

sim_state = SimState(
    innings=1,
    score=0,
    wickets_lost=0,
    balls_remaining=120,
    target_runs=None,
    batting_team='GGW',
    bowling_team='UPW',
    venue='Unknown',
    league='wpl',
    batting_team_win_rate=0.50,
    bowling_team_win_rate=0.40,
    batting_team_situation_wr=0.49,
    bowling_team_situation_wr=0.46
)

# Build FeatureContext
ctx = predictor.build_feature_context(
    batting_team='GGW',
    bowling_team='UPW',
    venue='Unknown',
    league='wpl',
    innings=1
    # Don't pass season stats - use historical from feature store like baseline does
)

print('1. predict() - uses RealTimeFeatureMapper')
prob_predict = predictor.predict(inference_state, debug=False)
print(f'   Prediction: {prob_predict:.1%}')
print()

print('2. predict_batch() - uses vectorized features + FeatureContext')
prob_batch = predictor.predict_batch([sim_state], feature_context=ctx)[0]
print(f'   Prediction: {prob_batch:.1%}')
print()

gap = abs(prob_predict - prob_batch) * 100
print(f'3. Gap: {gap:.1f}pp')
print()

if gap > 5:
    print('⚠️  LARGE GAP - Features are likely different!')
    print('    Need to extract and compare feature DataFrames')
else:
    print('✓  Small gap - likely just calibration or rounding differences')
