"""
IPL v7 Training Script — MC-augmented model.

What this does:
  1. Loads the full MC cache generated by analyze_ipl_mc_features_experiment.py
  2. Fits per-innings Platt calibrators on ALL training rows (saved for inference)
  3. Replaces resource_win_prob with MC-calibrated output in training features
  4. Trains XGBLogRegEnsemble on the MC-swapped features
  5. Runs OOF analysis to generate per-over isotonic calibrators (same as v6)
  6. Saves model + calibrators to models/ipl_v7/

Usage:
  python scripts/train_ipl_v7.py \\
    --features data/ipl_features_v6/training_sampled.parquet \\
    --mc-cache experiments/ipl_mc_features_v1_full200/mc_feature_cache.parquet \\
    --output-dir models/ipl_v7

At inference, you then need to:
  1. Run MC simulation (200 sims) for the current ball state
  2. Apply mc_platt_calibrators.pkl to get calibrated mc_win_prob
  3. Set resource_win_prob = calibrated mc_win_prob in the feature vector
  4. Call champion_model.joblib as normal
"""

import argparse
import hashlib
import json
import sys
import time
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import brier_score_loss

# ── repo root on path ────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from bbl_pipeline.training.trainer import XGBLogRegEnsemble  # noqa: E402


# ---------------------------------------------------------------------------
# Platt calibration helpers (shared with experiment script)
# ---------------------------------------------------------------------------

def safe_logit(p: np.ndarray, eps: float = 1e-7) -> np.ndarray:
    p = np.clip(p, eps, 1 - eps)
    return np.log(p / (1 - p))


def fit_platt_calibrators(
    mc_raw: np.ndarray,
    labels: np.ndarray,
    innings: np.ndarray,
) -> dict:
    """Fit per-innings Platt calibrators on ALL training data."""
    calibrators = {}
    for inn in [1, 2]:
        mask = innings == inn
        if mask.sum() < 50:
            continue
        X = safe_logit(mc_raw[mask]).reshape(-1, 1)
        lr = LogisticRegression(C=1e6, max_iter=1000, solver="lbfgs", random_state=42)
        lr.fit(X, labels[mask])
        calibrators[inn] = lr
        coef = lr.coef_[0][0]
        intercept = lr.intercept_[0]
        print(f"  Inn{inn} Platt: coef={coef:.4f}, intercept={intercept:.4f}, n={mask.sum()}")
    return calibrators


def apply_platt(
    mc_raw: np.ndarray, innings: np.ndarray, calibrators: dict
) -> np.ndarray:
    out = mc_raw.copy()
    for inn in [1, 2]:
        mask = innings == inn
        if not mask.any() or inn not in calibrators:
            continue
        X = safe_logit(mc_raw[mask]).reshape(-1, 1)
        out[mask] = calibrators[inn].predict_proba(X)[:, 1]
    return out


# ---------------------------------------------------------------------------
# OOF isotonic calibrator (same method as v6 generate-oof)
# ---------------------------------------------------------------------------

def generate_oof_isotonic(
    X: pd.DataFrame,
    y: np.ndarray,
    innings: np.ndarray,
    n_splits: int = 5,
) -> dict:
    """
    Generate per-innings isotonic calibrators via OOF cross-validation.
    Replicates the logic from bbl-pipeline generate-oof.
    """
    from sklearn.isotonic import IsotonicRegression

    n = len(X)
    fold_size = n // n_splits
    oof_raw = np.full(n, np.nan)

    for k in range(n_splits):
        val_start = k * fold_size
        val_end = (k + 1) * fold_size if k < n_splits - 1 else n
        train_idx = list(range(0, val_start)) + list(range(val_end, n))
        val_idx = list(range(val_start, val_end))
        if not train_idx:
            continue
        m = XGBLogRegEnsemble(n_features=32)
        m.fit(X.iloc[train_idx], y[train_idx])
        oof_raw[val_idx] = m.predict_proba(X.iloc[val_idx])[:, 1]

    calibrators = {}
    for inn in [1, 2]:
        mask = (innings == inn) & ~np.isnan(oof_raw)
        if mask.sum() < 50:
            continue
        iso = IsotonicRegression(out_of_bounds="clip")
        iso.fit(oof_raw[mask], y[mask])
        calibrators[inn] = iso
        oof_brier_raw = brier_score_loss(y[mask], oof_raw[mask])
        oof_brier_cal = brier_score_loss(y[mask], iso.predict(oof_raw[mask]))
        print(f"  Inn{inn} isotonic: raw Brier={oof_brier_raw:.4f} -> cal={oof_brier_cal:.4f}")

    return calibrators, oof_raw


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(description="Train IPL v7 model with MC-swapped resource_win_prob")
    p.add_argument("--features", required=True, help="Path to training features parquet (ipl_features_v6)")
    p.add_argument("--mc-cache", required=True, help="Path to MC cache parquet (from experiment script)")
    p.add_argument("--output-dir", required=True, help="Output directory for IPL v7 model")
    p.add_argument("--n-oof-splits", type=int, default=5, help="OOF splits for isotonic calibrator")
    p.add_argument("--skip-oof", action="store_true", help="Skip OOF isotonic calibrator generation")
    return p.parse_args()


def main():
    args = parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    t0 = time.time()
    print(f"\n{'=' * 64}")
    print("  IPL v7 Training -- MC-augmented model")
    print(f"  Features:  {args.features}")
    print(f"  MC cache:  {args.mc_cache}")
    print(f"  Output:    {output_dir}")
    print(f"{'=' * 64}\n")

    # ── Step 1: Load data ────────────────────────────────────────────────────
    print("[1/5] Loading training data...")
    df = pd.read_parquet(args.features)
    df = df.reset_index(drop=True)
    print(f"  Loaded {len(df):,} rows x {len(df.columns)} columns")

    cache_df = pd.read_parquet(args.mc_cache)
    cache_ok = cache_df[cache_df["sim_ok"]].set_index("row_key")
    n_cached = len(cache_ok)
    print(f"  MC cache: {n_cached:,} rows ({len(cache_df):,} total, {len(cache_df) - n_cached} skipped)")

    # ── Step 2: Align MC cache to features ──────────────────────────────────
    print("\n[2/5] Aligning MC cache and fitting Platt calibrators...")
    eligible = np.array([i in cache_ok.index for i in range(len(df))])
    elig_idx = np.where(eligible)[0]
    n_elig = len(elig_idx)
    print(f"  Eligible rows: {n_elig:,} / {len(df):,} ({100*n_elig/len(df):.1f}%)")

    df_elig = df.iloc[elig_idx].reset_index(drop=True)
    mc_raw = cache_ok.loc[elig_idx, "mc_raw_win_prob"].values.astype(float)
    innings = df_elig["innings"].values.astype(int)
    labels = df_elig["is_winner"].values.astype(float)

    # Fit Platt calibrators on ALL eligible training data
    platt_calibrators = fit_platt_calibrators(mc_raw, labels, innings)
    mc_cal = apply_platt(mc_raw, innings, platt_calibrators)

    # Save Platt calibrators for inference
    platt_path = output_dir / "mc_platt_calibrators.pkl"
    joblib.dump(platt_calibrators, platt_path)
    print(f"  Saved Platt calibrators -> {platt_path}")

    # Quick pre/post Brier for MC signal quality
    for inn in [1, 2]:
        mask = innings == inn
        if not mask.any():
            continue
        b_raw = brier_score_loss(labels[mask], mc_raw[mask])
        b_cal = brier_score_loss(labels[mask], mc_cal[mask])
        print(f"  Inn{inn} MC Brier: raw={b_raw:.4f} -> platt_cal={b_cal:.4f}")

    # ── Step 3: Build MC-swapped training features ───────────────────────────
    print("\n[3/5] Building MC-swapped feature matrix...")
    X = df_elig.copy()
    X["resource_win_prob"] = mc_cal  # clean swap: same 32 features, MC values
    y = labels

    baseline_brier = brier_score_loss(y, X["resource_win_prob"])
    print(f"  resource_win_prob (MC) Brier as standalone: {baseline_brier:.4f}")
    print(f"  Feature matrix: {X.shape}")

    # ── Step 4: Train full model ─────────────────────────────────────────────
    print("\n[4/5] Training XGBLogRegEnsemble on MC-swapped features...")
    model = XGBLogRegEnsemble(n_features=32)
    model.fit(X, y)

    train_probs = model.predict_proba(X)[:, 1]
    train_brier = brier_score_loss(y, train_probs)
    print(f"  Train Brier (in-sample, optimistic): {train_brier:.4f}")

    # Feature importance
    try:
        fi = model.get_feature_importance()
        fi_path = output_dir / "feature_importance.csv"
        fi.to_csv(fi_path, index=False)
        print(f"  Feature importance -> {fi_path}")
        top5 = fi.head(5)
        for _, row in top5.iterrows():
            print(f"    #{int(row.get('rank', 0))}: {row['feature']} = {row['importance']:.4f}")
    except Exception as e:
        print(f"  Warning: could not get feature importance: {e}")

    # Save champion model
    model_path = output_dir / "champion_model.joblib"
    joblib.dump(model, model_path)
    print(f"  Saved model -> {model_path}")

    # ── Step 5: OOF isotonic calibrators ────────────────────────────────────
    if not args.skip_oof:
        print(f"\n[5/5] Generating OOF isotonic calibrators ({args.n_oof_splits}-fold)...")
        print("  (This retrains the model N times — may take a few minutes)")
        oof_calibrators, oof_raw = generate_oof_isotonic(X, y, innings, n_splits=args.n_oof_splits)

        # Save OOF calibrators in the same format as bbl-pipeline generate-oof
        oof_cal_path = output_dir / "oof_calibrators.pkl"
        joblib.dump({"per_over": None, "innings_specific": oof_calibrators}, oof_cal_path)
        print(f"  Saved OOF calibrators -> {oof_cal_path}")

        # Save isotonic_calibrator.pkl (used by predictor and Streamlit app)
        iso_path = output_dir / "isotonic_calibrator.pkl"
        joblib.dump(oof_calibrators, iso_path)
        print(f"  Saved isotonic calibrator -> {iso_path}")

        # OOF overall Brier
        valid = ~np.isnan(oof_raw)
        oof_brier = brier_score_loss(y[valid], oof_raw[valid])
        print(f"\n  OOF Brier (raw model, no cal): {oof_brier:.4f}")

        oof_cal_probs = apply_platt(oof_raw[valid], innings[valid],
                                     {inn: oof_calibrators[inn] for inn in oof_calibrators})
        oof_brier_cal = brier_score_loss(y[valid], oof_cal_probs)
        print(f"  OOF Brier (+ isotonic cal):    {oof_brier_cal:.4f}")

        # Compare vs IPL v6 baseline
        print(f"\n  IPL v6 OOF Brier (reference):  0.1811")
        print(f"  IPL v7 OOF Brier (MC-swapped): {oof_brier:.4f}  (delta={oof_brier - 0.1811:+.4f})")
    else:
        print("\n[5/5] Skipping OOF (--skip-oof)")
        oof_brier = None

    # ── Save metadata ────────────────────────────────────────────────────────
    data_hash = hashlib.sha256(df_elig.to_json().encode()).hexdigest()
    metadata = {
        "model_name": "ensemble",
        "model_version": "ipl_v7",
        "description": "IPL v7: XGBLogRegEnsemble with MC-calibrated resource_win_prob (200 sims, 6-ball horizon)",
        "base_model_params": model.get_params(),
        "mc_settings": {
            "n_sims": 200,
            "horizon_balls": 6,
            "calibration": "platt_per_innings",
        },
        "training_rows": n_elig,
        "oof_brier": round(oof_brier, 6) if oof_brier is not None else None,
        "ipl_v6_oof_brier_reference": 0.1811,
        "data_version_hash": data_hash,
        "mc_cache": str(Path(args.mc_cache).resolve()),
        "features_source": str(Path(args.features).resolve()),
    }
    meta_path = output_dir / "champion_metadata.json"
    meta_path.write_text(json.dumps(metadata, indent=2))
    print(f"\n  Metadata -> {meta_path}")

    elapsed = time.time() - t0
    print(f"\n{'=' * 64}")
    print(f"  IPL v7 training complete in {elapsed:.1f}s")
    print(f"  Output: {output_dir}")
    print(f"{'=' * 64}\n")

    print("  Inference checklist:")
    print("  1. Run MC sim (200 sims, 6-ball horizon) for live ball state")
    print("  2. Load mc_platt_calibrators.pkl, apply to mc_raw_win_prob")
    print("  3. Set feature['resource_win_prob'] = calibrated mc prob")
    print("  4. Call champion_model.joblib.predict_proba(features)")
    print("  5. Apply oof_calibrators.pkl for final calibration")


if __name__ == "__main__":
    main()
