"""Offline IPL state embedding helpers."""

from .corpus import build_embedding_corpus, load_input_and_context
from .embeddings import fit_embedding_models, select_numeric_feature_columns
from .evaluation import (
    PHASE_DEATH,
    PHASE_MIDDLE,
    PHASE_POWERPLAY,
    add_reference_deltas,
    add_baseline_deltas,
    apply_inn2_powerplay_variant,
    apply_guarded_regime_phase_calibration,
    build_regime_feature_frame,
    check_go_no_go,
    collect_reliability_bins,
    collect_segment_metrics,
    compute_brier,
    compute_ece,
    compute_log_loss_metric,
    fit_guarded_regime_phase_calibration,
    get_phase_label,
    make_season_slices,
    make_train_before_test_season_split,
    make_time_ordered_cv_splits,
    make_time_ordered_holdout_split,
    render_pilot_report,
    summarize_guarded_regime_phase_calibration,
    summarize_regimes,
)
from .retrieval import build_analogue_features, query_historical_analogues

__all__ = [
    "PHASE_DEATH",
    "PHASE_MIDDLE",
    "PHASE_POWERPLAY",
    "add_reference_deltas",
    "add_baseline_deltas",
    "apply_inn2_powerplay_variant",
    "apply_guarded_regime_phase_calibration",
    "build_analogue_features",
    "build_embedding_corpus",
    "build_regime_feature_frame",
    "check_go_no_go",
    "collect_reliability_bins",
    "collect_segment_metrics",
    "compute_brier",
    "compute_ece",
    "compute_log_loss_metric",
    "fit_embedding_models",
    "fit_guarded_regime_phase_calibration",
    "get_phase_label",
    "load_input_and_context",
    "make_season_slices",
    "make_train_before_test_season_split",
    "make_time_ordered_cv_splits",
    "make_time_ordered_holdout_split",
    "query_historical_analogues",
    "render_pilot_report",
    "select_numeric_feature_columns",
    "summarize_guarded_regime_phase_calibration",
    "summarize_regimes",
]
